import type { LevelConfig } from "./types";

export const levelConfigs: LevelConfig[] = [
  {
    levelNumber: "1",
    titleKey: "t41",
    subtitle: "Phonics & Early Reading",
    ageGroup: "Ages 5-6",
    duration: "36 Weeks | 2-3 Sessions/Week | 30-40 Min/Session",
    aim: "To introduce students to phonics, letter recognition, basic sight words, and the joy of reading through interactive games, storytelling, and hands-on activities.",
    units: [
      { no: 1, topic: "Letter Recognition", skills: "Identify all 26 letters, uppercase and lowercase" },
      { no: 2, topic: "Phonetic Sounds", skills: "Understand letter sounds and phoneme combinations" },
      { no: 3, topic: "Sight Words", skills: "Recognize and read common high-frequency words (the, is, at, etc.)" },
      { no: 4, topic: "Simple CVC Words", skills: "Read consonant-vowel-consonant patterns (cat, dog, run)" },
      { no: 5, topic: "Rhyming & Rhythm", skills: "Identify rhyming words, clap syllables, nursery rhymes" },
      { no: 6, topic: "Story Comprehension", skills: "Answer simple questions about short stories read aloud" },
      { no: 7, topic: "Alphabet Writing", skills: "Trace and write letters correctly" },
      { no: 8, topic: "Simple Sentences", skills: "Read and understand simple 3-4 word sentences" },
    ],
  },
  {
    levelNumber: "2",
    titleKey: "t37",
    subtitle: "Building Blocks to Reading",
    ageGroup: "Ages 6-7",
    duration: "36 Weeks | 2 Sessions/Week | 40 Min/Session",
    aim: "To develop fluency in reading, introduce beginning writing skills, expand vocabulary, and build comprehension through diverse texts and writing exercises.",
    units: [
      { no: 1, topic: "Blending & Digraphs", skills: "Blend sounds into words (ch, sh, th, ng)" },
      { no: 2, topic: "Word Families", skills: "Recognize patterns and rhyme families (at, et, og families)" },
      { no: 3, topic: "Reading Fluency", skills: "Read decodable texts with growing accuracy and speed" },
      { no: 4, topic: "Vocabulary Expansion", skills: "Learn new words in context from picture books" },
      { no: 5, topic: "Sentence Structure", skills: "Understand subject-verb, simple sentence construction" },
      { no: 6, topic: "Story Retelling", skills: "Retell stories with beginning, middle, and end" },
      { no: 7, topic: "Writing Letters & Words", skills: "Write simple words and copy sentences" },
      { no: 8, topic: "Listening & Speaking", skills: "Follow directions, express ideas in complete sentences" },
    ],
  },
  {
    levelNumber: "3",
    titleKey: "t34",
    subtitle: "Confident Readers & Writers",
    ageGroup: "Ages 7-8",
    duration: "36 Weeks | 2 Sessions/Week | 45 Min/Session",
    aim: "To establish reading confidence, introduce varied text types, develop writing skills from sentences to paragraphs, and enhance vocabulary and comprehension.",
    units: [
      { no: 1, topic: "Reading Different Genres", skills: "Fiction, non-fiction, poetry, simple informational texts" },
      { no: 2, topic: "Phonics Mastery", skills: "Advanced phonetic patterns, silent letters, irregular words" },
      { no: 3, topic: "Vocabulary Development", skills: "Synonyms, antonyms, context clues, word definitions" },
      { no: 4, topic: "Comprehension Skills", skills: "Predict, summarize, identify main idea and details" },
      { no: 5, topic: "Writing Sentences", skills: "Construct complete sentences with capitals and periods" },
      { no: 6, topic: "Paragraph Writing", skills: "Write 2-3 sentence paragraphs on familiar topics" },
      { no: 7, topic: "Grammar Foundations", skills: "Nouns, verbs, adjectives, simple tenses" },
      { no: 8, topic: "Public Speaking", skills: "Present ideas, answer questions, read aloud with expression" },
    ],
  },
  {
    levelNumber: "4",
    titleKey: "t39",
    subtitle: "Fluent Readers & Young Authors",
    ageGroup: "Ages 8-9",
    duration: "36 Weeks | 2 Sessions/Week | 45 Min/Session",
    aim: "To develop deeper reading comprehension, introduce multi-paragraph writing, expand grammar understanding, and foster a love of literature through chapter books.",
    units: [
      { no: 1, topic: "Chapter Books", skills: "Read and comprehend age-appropriate chapter books" },
      { no: 2, topic: "Inference & Analysis", skills: "Make inferences, identify theme, analyze character motivation" },
      { no: 3, topic: "Literary Devices", skills: "Understand simile, metaphor, personification, hyperbole" },
      { no: 4, topic: "Paragraph Structure", skills: "Topic sentence, supporting details, conclusion" },
      { no: 5, topic: "Writing Narratives", skills: "Write short stories with setting, characters, plot" },
      { no: 6, topic: "Descriptive Writing", skills: "Use sensory details, vivid adjectives, strong verbs" },
      { no: 7, topic: "Grammar & Mechanics", skills: "Compound sentences, punctuation, apostrophes, contractions" },
      { no: 8, topic: "Research Skills", skills: "Find information, take notes, create simple reports" },
    ],
  },
  {
    levelNumber: "5",
    titleKey: "t40",
    subtitle: "Critical Readers & Proficient Writers",
    ageGroup: "Ages 9-10",
    duration: "36 Weeks | 2 Sessions/Week | 50 Min/Session",
    aim: "To develop critical thinking about texts, strengthen composition skills, introduce expository and persuasive writing, and expand knowledge of grammar and vocabulary.",
    units: [
      { no: 1, topic: "Text Analysis", skills: "Distinguish fact from opinion, evaluate sources, identify bias" },
      { no: 2, topic: "Expository Writing", skills: "How-to, explanatory essays, structured paragraphs" },
      { no: 3, topic: "Persuasive Writing", skills: "Write persuasive essays with claims and evidence" },
      { no: 4, topic: "Narrative Development", skills: "Complex storylines, character development, dialogue" },
      { no: 5, topic: "Complex Grammar", skills: "Complex sentences, subordinate clauses, conjunctions" },
      { no: 6, topic: "Vocabulary Mastery", skills: "Root words, prefixes, suffixes, word relationships" },
      { no: 7, topic: "Spelling & Conventions", skills: "Master challenging spellings, proper punctuation, formatting" },
      { no: 8, topic: "Research & Citations", skills: "Gather sources, organize information, create bibliographies" },
    ],
  },
  {
    levelNumber: "6",
    titleKey: "t32",
    subtitle: "Advanced Reading Comprehension",
    ageGroup: "Ages 10-11",
    duration: "36 Weeks | 2 Sessions/Week | 50 Min/Session",
    aim: "To deepen literary analysis, refine writing across multiple genres, master complex grammar, and develop academic reading and writing skills.",
    units: [
      { no: 1, topic: "Advanced Literature", skills: "Analyze themes, symbolism, author's purpose, tone" },
      { no: 2, topic: "Fiction & Poetry", skills: "Understand structure, rhyme schemes, narrative techniques" },
      { no: 3, topic: "Non-Fiction Mastery", skills: "Reading comprehension, extracting key information from texts" },
      { no: 4, topic: "Academic Writing", skills: "Essays, reports, structured arguments with evidence" },
      { no: 5, topic: "Advanced Mechanics", skills: "Complex punctuation, semicolons, colons, dashes" },
      { no: 6, topic: "Vocabulary Expansion", skills: "Etymology, context, nuanced word choice" },
      { no: 7, topic: "Research Projects", skills: "Conduct research, synthesize sources, write documented essays" },
      { no: 8, topic: "Speaking & Debate", skills: "Present arguments, engage in discussions, formal presentations" },
    ],
  },
  {
    levelNumber: "7",
    titleKey: "t35",
    subtitle: "Secondary English — GCSE/KS4 Foundations",
    ageGroup: "Ages 11-13",
    duration: "36 Weeks | 2 Sessions/Week | 55 Min/Session",
    aim: "To prepare for GCSE English Literature and Language, analyzing complex texts, refining persuasive and analytical writing, and mastering formal academic English.",
    units: [
      { no: 1, topic: "Shakespeare Introduction", skills: "Read and analyze key scenes, understand historical context" },
      { no: 2, topic: "Literary Analysis", skills: "Analyze character, setting, plot, themes, and literary devices" },
      { no: 3, topic: "Reading Non-Fiction", skills: "Analyze structure, style, persuasive techniques, tone" },
      { no: 4, topic: "Writing Essays", skills: "Multi-paragraph essays with thesis, evidence, analysis" },
      { no: 5, topic: "Persuasive Techniques", skills: "Rhetorical devices, ethos, pathos, logos, emotive language" },
      { no: 6, topic: "Standard English Grammar", skills: "Complex clauses, voice (active/passive), mood, tense" },
      { no: 7, topic: "GCSE Preparation", skills: "Answer exam-style questions, time management, essay planning" },
      { no: 8, topic: "Vocabulary for GCSE", skills: "Academic terminology, precise word choices, sophisticated language" },
    ],
  },
  {
    levelNumber: "8",
    titleKey: "t33",
    subtitle: "GCSE English Literature & Language Excellence",
    ageGroup: "Ages 13-14",
    duration: "36 Weeks | 2 Sessions/Week | 60 Min/Session",
    aim: "To achieve excellence in GCSE English Literature and Language, master textual analysis, produce sophisticated writing, and develop critical thinking skills.",
    units: [
      { no: 1, topic: "Shakespeare & Drama", skills: "Deep textual analysis, performance interpretation, examiner-style answers" },
      { no: 2, topic: "Poetry Anthology", skills: "Compare poems, identify themes, analyze poetic devices expertly" },
      { no: 3, topic: "19th Century Novels", skills: "Analyze historical fiction, characterization, social context" },
      { no: 4, topic: "Modern Texts", skills: "Explore contemporary literature, cultural context, diverse perspectives" },
      { no: 5, topic: "Analytical Essays", skills: "Develop sophisticated arguments, integrate quotations seamlessly" },
      { no: 6, topic: "Creative Writing", skills: "Narrative, descriptive, and transactional writing at GCSE level" },
      { no: 7, topic: "Speaking & Listening", skills: "Present arguments orally, engage in formal discussions, debate" },
      { no: 8, topic: "GCSE Exam Technique", skills: "Time management, question analysis, mark maximization strategies" },
    ],
  },
];
