import type { LevelConfig } from "./types";

export const levelConfigs: LevelConfig[] = [
  {
    levelNumber: "1",
    titleKey: "t41",
    subtitle: "Computational Thinking Foundations",
    ageGroup: "Ages 6-7",
    duration: "36 Weeks | 1-2 Sessions/Week | 30-40 Min/Session",
    aim: "To introduce sequencing, algorithms, and the concept of instructions through unplugged activities, then transition into Scratch Jr on tablet.",
    units: [
      { no: 1, topic: "What is a Computer?", skills: "Hardware and Software Basics" },
      { no: 2, topic: "Algorithms", skills: "Giving and following instructions" },
      { no: 3, topic: "Sequences", skills: "Step-by-Step Thinking (Unplugged)" },
      { no: 4, topic: "Debugging", skills: "Fixing mistakes in instructions" },
      { no: 5, topic: "Introduction to Scratch Jr", skills: "Navigating the App" },
      { no: 6, topic: "Scratch Jr - Moving and Animating", skills: "Motion and looks blocks" },
      { no: 7, topic: "Scratch Jr - Events and Loops", skills: "Trigger scripts, repeat actions" },
      { no: 8, topic: "Scratch Jr - Project", skills: "Create a Simple Story" },
    ],
  },
  {
    levelNumber: "2",
    titleKey: "t37",
    subtitle: "Beginner Coding",
    ageGroup: "Ages 7-8",
    duration: "36 Weeks | 2 Sessions/Week | 40 Min/Session",
    aim: "To develop logical thinking, sequencing, loops, and conditionals through Scratch 3.0 visual block programming, culminating in a complete game project.",
    units: [
      { no: 1, topic: "Scratch 3.0 Interface", skills: "Sprites, Stage, Costumes, Sounds" },
      { no: 2, topic: "Motion and Looks Blocks", skills: "Move sprites, change costumes" },
      { no: 3, topic: "Events", skills: "When Key Pressed, When Flag Clicked" },
      { no: 4, topic: "Loops", skills: "Repeat, Repeat Until, Forever" },
      { no: 5, topic: "Conditionals", skills: "if / if-else Blocks" },
      { no: 6, topic: "Variables", skills: "Score, Timer, Counter" },
      { no: 7, topic: "Broadcasting", skills: "Sprites Communicating" },
      { no: 8, topic: "Project", skills: "Build a Complete Game in Scratch" },
    ],
  },
  {
    levelNumber: "3",
    titleKey: "t34",
    subtitle: "Deepening Logic",
    ageGroup: "Ages 8-9",
    duration: "36 Weeks | 2 Sessions/Week | 45 Min/Session",
    aim: "To deepen Scratch skills, introduce core computer science concepts including decomposition, abstraction, and data structures, and build interactive projects.",
    units: [
      { no: 1, topic: "Decomposition", skills: "Breaking big problems into small steps" },
      { no: 2, topic: "Abstraction", skills: "Focusing on what matters, simplify" },
      { no: 3, topic: "User Input", skills: "Ask and Answer blocks" },
      { no: 4, topic: "Lists", skills: "Storing multiple items" },
      { no: 5, topic: "Clones", skills: "Creating copies of sprites" },
      { no: 6, topic: "Custom Blocks (My Blocks)", skills: "Introduction to Functions" },
      { no: 7, topic: "Number Systems", skills: "Binary and Hexadecimal" },
      { no: 8, topic: "Project", skills: "Multi-level Game or Interactive Quiz" },
    ],
  },
  {
    levelNumber: "4",
    titleKey: "t39",
    subtitle: "Text-based Programming",
    ageGroup: "Ages 9-10",
    duration: "36 Weeks | 2 Sessions/Week | 45 Min/Session",
    aim: "To transition from block coding to real text-based programming using Python 3, covering core syntax, data types, control flow, and functions.",
    units: [
      { no: 1, topic: "Introduction to Python", skills: "Why text code?, write first program" },
      { no: 2, topic: "Print, Input, Comments", skills: "Run programs, track errors" },
      { no: 3, topic: "Variables and Data Types", skills: "str, int, float, bool" },
      { no: 4, topic: "Arithmetic Operators", skills: "Calculate, PEMDAS in code" },
      { no: 5, topic: "Conditionals", skills: "if, elif, else" },
      { no: 6, topic: "Loops", skills: "for and while, range()" },
      { no: 7, topic: "Functions", skills: "def, parameters, return values" },
      { no: 8, topic: "Lists", skills: "Create, index, slice, loop" },
      { no: 9, topic: "Strings", skills: "Methods, formatting, f-strings" },
      { no: 10, topic: "Project", skills: "Text-Based Adventure Game" },
    ],
  },
  {
    levelNumber: "5",
    titleKey: "t40",
    subtitle: "Object-Oriented & Applied Python",
    ageGroup: "Ages 10-11",
    duration: "36 Weeks | 2 Sessions/Week | 50 Min/Session",
    aim: "To develop intermediate Python skills including dictionaries, modules, file handling, error handling, and an introduction to object-oriented programming.",
    units: [
      { no: 1, topic: "Dictionaries", skills: "Key-Value pairs, maps" },
      { no: 2, topic: "Tuples and Sets", skills: "Immutability, uniqueness" },
      { no: 3, topic: "File Handling", skills: "Read/write text and CSV" },
      { no: 4, topic: "Importing Modules", skills: "math, random, datetime, os" },
      { no: 5, topic: "Error Handling", skills: "try, except, finally blocks" },
      { no: 6, topic: "OOP - Classes", skills: "Attributes, methods, self" },
      { no: 7, topic: "OOP - Inheritance", skills: "Subclasses, polymorphism" },
      { no: 8, topic: "Recursion", skills: "Functions calling themselves" },
      { no: 9, topic: "Algorithms", skills: "Sorting, Binary Search" },
      { no: 10, topic: "Project", skills: "Python App with File Storage" },
    ],
  },
  {
    levelNumber: "6",
    titleKey: "t32",
    subtitle: "Web Development Basics",
    ageGroup: "Ages 11-12",
    duration: "36 Weeks | 2 Sessions/Week | 50 Min/Session",
    aim: "To introduce the structure and presentation of web pages using HTML and CSS, enabling students to design and build complete, styled websites.",
    units: [
      { no: 1, topic: "How the Web Works", skills: "Servers, Clients, HTTP" },
      { no: 2, topic: "HTML Structure", skills: "Document structure, tags, elements" },
      { no: 3, topic: "HTML Content", skills: "Text, links, images, tables" },
      { no: 4, topic: "HTML Forms", skills: "Input, select, submit securely" },
      { no: 5, topic: "CSS Styling", skills: "Selectors, properties, box model" },
      { no: 6, topic: "CSS Layouts", skills: "Flexbox and Grid layouts" },
      { no: 7, topic: "CSS Animations", skills: "Transitions, keyframes, variables" },
      { no: 8, topic: "Responsive Design", skills: "Media queries for mobile/desktop" },
      { no: 9, topic: "Accessibility", skills: "ARIA, semantic HTML" },
      { no: 10, topic: "Project", skills: "Deploy a Complete Personal Website" },
    ],
  },
  {
    levelNumber: "7",
    titleKey: "t35",
    subtitle: "Frontend Engineering",
    ageGroup: "Ages 12-13",
    duration: "36 Weeks | 2 Sessions/Week | 55 Min/Session",
    aim: "To add interactivity and logic to web pages using JavaScript, covering DOM manipulation, events, APIs, and the foundations of modern web development.",
    units: [
      { no: 1, topic: "JS Syntax", skills: "Variables, types, operators" },
      { no: 2, topic: "Core Logic in JS", skills: "Functions, conditionals, loops" },
      { no: 3, topic: "The DOM", skills: "Selecting and manipulating elements" },
      { no: 4, topic: "Events", skills: "Click, keypress, form submit" },
      { no: 5, topic: "Data Structures in JS", skills: "Arrays, Objects, iteration" },
      { no: 6, topic: "Asynchronous JavaScript", skills: "Promises, setTimeout, Fetch" },
      { no: 7, topic: "Working with JSON", skills: "Parsing and displaying dynamic API data" },
      { no: 8, topic: "Intro to React", skills: "Components, props, state (basics)" },
      { no: 9, topic: "Version Control", skills: "Git and GitHub workflows" },
      { no: 10, topic: "Project", skills: "Dynamic App Deployment via Actions" },
    ],
  },
  {
    levelNumber: "8",
    titleKey: "t33",
    subtitle: "Applied Programming Skills",
    ageGroup: "Ages 13-14",
    duration: "36 Weeks | 2 Sessions/Week | 55 Min/Session",
    aim: "To apply Python to real-world domains including data science, automation, APIs, and databases, and develop professional programming practices.",
    units: [
      { no: 1, topic: "Data Structures", skills: "Stacks, Queues, Linked Lists" },
      { no: 2, topic: "Working with APIs", skills: "Requests, JSON, Auth" },
      { no: 3, topic: "Data Analysis", skills: "NumPy and Pandas" },
      { no: 4, topic: "Data Visualisation", skills: "Matplotlib and Seaborn" },
      { no: 5, topic: "Automation", skills: "Web Scraping with BeautifulSoup" },
      { no: 6, topic: "Databases", skills: "SQLite with Python, SQLAlchemy" },
      { no: 7, topic: "Testing", skills: "Unit Tests with unittest/pytest" },
      { no: 8, topic: "Regular Expressions", skills: "Pattern matching, extraction" },
      { no: 9, topic: "Command Line Tools", skills: "argparse, automation scripts" },
      { no: 10, topic: "Project", skills: "Real-World Data Processing Pipeline" },
    ],
  },
  {
    levelNumber: "9",
    titleKey: "t38",
    subtitle: "GCSE / A-Level CS Preparation",
    ageGroup: "Ages 14-15",
    duration: "36 Weeks | 2 Sessions/Week | 60 Min/Session",
    aim: "To study formal computer science theory including computational thinking, data representation, computer architecture, networks, and cybersecurity.",
    units: [
      { no: 1, topic: "Computational Thinking", skills: "Decomposition, abstraction, algorithms" },
      { no: 2, topic: "Data Representation", skills: "Binary, Hex, ASCII, Unicode" },
      { no: 3, topic: "Computer Architecture", skills: "CPU, Memory, FDE cycle" },
      { no: 4, topic: "Networks", skills: "Topologies, Protocols, TCP/IP" },
      { no: 5, topic: "Cybersecurity", skills: "Threats, Encryption, Authentication" },
      { no: 6, topic: "Databases", skills: "Relational Design, SQL, Normalisation" },
      { no: 7, topic: "Big Data & AI", skills: "Machine Learning concepts, Ethics" },
      { no: 8, topic: "Ethics & Law", skills: "IP, Privacy, Digital Footprints" },
      { no: 9, topic: "Programming Paradigms", skills: "Procedural, OOP, Functional" },
      { no: 10, topic: "Examination Technique", skills: "Trace tables, Pseudo-code" },
    ],
  },
  {
    levelNumber: "10",
    titleKey: "t36",
    subtitle: "Professional Portfolio",
    ageGroup: "Ages 15-16",
    duration: "36 Weeks | 2 Sessions/Week | 60 Min/Session",
    aim: "To consolidate all programming knowledge into a full-stack development capstone, building a real application and a professional portfolio ready for further study or work.",
    units: [
      { no: 1, topic: "System Design", skills: "Architecture, Planning, Scale" },
      { no: 2, topic: "Backend Development", skills: "Flask/Django, Routes, APIs" },
      { no: 3, topic: "Frontend Development", skills: "React + Tailwind/Bootstrap" },
      { no: 4, topic: "Database Integration", skills: "PostgreSQL, Models, ORM" },
      { no: 5, topic: "Auth & Security", skills: "Login, Sessions, JWT, Hashing" },
      { no: 6, topic: "Deployment", skills: "Docker, Cloud Hosting (Render/AWS)" },
      { no: 7, topic: "Agile Development", skills: "Sprints, Kanban, Teamwork" },
      { no: 8, topic: "Code Review", skills: "Pull Requests, CI/CD Actions" },
      { no: 9, topic: "Portfolio Production", skills: "Case studies, Demos, Write-up" },
      { no: 10, topic: "Capstone Project", skills: "Build, Deploy and Present" },
    ],
  },
];
