import type { LevelConfig } from "./types";

export const levelConfigs: LevelConfig[] = [
  {
    levelNumber: "1",
    titleKey: "t41",
    subtitle: "AI Foundations & Chatbots",
    ageGroup: "Ages 8-9",
    duration: "36 Weeks | 2 Sessions/Week | 40 Min/Session",
    aim: "To introduce artificial intelligence concepts through interactive experiences, understanding what AI is, how it thinks, and building simple chatbots.",
    units: [
      { no: 1, topic: "What is Artificial Intelligence?", skills: "Understand AI basics and real-world examples" },
      { no: 2, topic: "How Machines Learn", skills: "Introduction to machine learning concepts" },
      { no: 3, topic: "Pattern Recognition", skills: "Identify patterns in data and images" },
      { no: 4, topic: "Chatbot Basics", skills: "Create rule-based conversational agents" },
      { no: 5, topic: "Decision Trees", skills: "Build simple decision-making systems" },
      { no: 6, topic: "AI Ethics & Bias", skills: "Understand fairness and responsible AI" },
      { no: 7, topic: "Image Recognition Basics", skills: "Explore computer vision concepts" },
      { no: 8, topic: "Simple AI Projects", skills: "Build interactive AI applications" },
    ],
  },
  {
    levelNumber: "2",
    titleKey: "t37",
    subtitle: "Machine Learning Fundamentals",
    ageGroup: "Ages 9-10",
    duration: "36 Weeks | 2 Sessions/Week | 45 Min/Session",
    aim: "To develop understanding of machine learning workflows, supervised and unsupervised learning, and practical applications using Python.",
    units: [
      { no: 1, topic: "Python for AI", skills: "Python basics for data science and AI" },
      { no: 2, topic: "Data Collection & Preparation", skills: "Gather and clean data for ML models" },
      { no: 3, topic: "Supervised Learning", skills: "Classification and regression basics" },
      { no: 4, topic: "Unsupervised Learning", skills: "Clustering and pattern discovery" },
      { no: 5, topic: "Training & Testing Data", skills: "Split data, validate models" },
      { no: 6, topic: "Model Evaluation", skills: "Accuracy, precision, recall metrics" },
      { no: 7, topic: "Introduction to TensorFlow", skills: "Use ML libraries and frameworks" },
      { no: 8, topic: "ML Mini-Projects", skills: "Build predictive models" },
    ],
  },
  {
    levelNumber: "3",
    titleKey: "t34",
    subtitle: "Deep Learning & Neural Networks",
    ageGroup: "Ages 10-11",
    duration: "36 Weeks | 2 Sessions/Week | 50 Min/Session",
    aim: "To understand neural networks, deep learning architectures, and apply them to real-world problems like image and text recognition.",
    units: [
      { no: 1, topic: "Neural Networks Basics", skills: "Understand neurons, layers, activation functions" },
      { no: 2, topic: "Forward & Backward Propagation", skills: "How neural networks learn and adjust weights" },
      { no: 3, topic: "Convolutional Neural Networks", skills: "Image processing and computer vision" },
      { no: 4, topic: "Recurrent Neural Networks", skills: "Processing sequential data and text" },
      { no: 5, topic: "Optimization Techniques", skills: "Gradient descent and advanced optimizers" },
      { no: 6, topic: "Transfer Learning", skills: "Reuse pre-trained models" },
      { no: 7, topic: "Building Models with Keras", skills: "Create sophisticated neural network architectures" },
      { no: 8, topic: "Deep Learning Projects", skills: "Image classification and text analysis" },
    ],
  },
  {
    levelNumber: "4",
    titleKey: "t39",
    subtitle: "Natural Language Processing (NLP)",
    ageGroup: "Ages 11-12",
    duration: "36 Weeks | 2 Sessions/Week | 50 Min/Session",
    aim: "To master natural language processing techniques, text analysis, and build intelligent systems that understand and generate human language.",
    units: [
      { no: 1, topic: "Text Processing Fundamentals", skills: "Tokenization, stemming, lemmatization" },
      { no: 2, topic: "Word Embeddings", skills: "Word2Vec, GloVe, and semantic representation" },
      { no: 3, topic: "Sentiment Analysis", skills: "Classify emotions and opinions in text" },
      { no: 4, topic: "Named Entity Recognition", skills: "Extract names, places, and entities" },
      { no: 5, topic: "Language Models", skills: "Transformers and attention mechanisms" },
      { no: 6, topic: "Machine Translation", skills: "Building translation systems" },
      { no: 7, topic: "Advanced NLP with BERT/GPT", skills: "Use state-of-the-art models" },
      { no: 8, topic: "NLP Applications", skills: "Build chatbots and text analysis tools" },
    ],
  },
  {
    levelNumber: "5",
    titleKey: "t40",
    subtitle: "Computer Vision Mastery",
    ageGroup: "Ages 12-13",
    duration: "36 Weeks | 2 Sessions/Week | 55 Min/Session",
    aim: "To develop advanced computer vision skills, understanding image processing, object detection, facial recognition, and real-world applications.",
    units: [
      { no: 1, topic: "Image Fundamentals", skills: "Pixels, channels, color spaces" },
      { no: 2, topic: "Image Filtering & Enhancement", skills: "Edge detection, blurring, sharpening" },
      { no: 3, topic: "Object Detection Models", skills: "YOLO, R-CNN architectures" },
      { no: 4, topic: "Facial Recognition", skills: "Face detection and verification systems" },
      { no: 5, topic: "Pose & Gesture Recognition", skills: "Understand body movements and actions" },
      { no: 6, topic: "Segmentation Techniques", skills: "Semantic and instance segmentation" },
      { no: 7, topic: "3D Vision", skills: "Depth estimation and 3D reconstruction" },
      { no: 8, topic: "Real-World CV Projects", skills: "Build autonomous vision systems" },
    ],
  },
  {
    levelNumber: "6",
    titleKey: "t32",
    subtitle: "Reinforcement Learning & Autonomous Systems",
    ageGroup: "Ages 13-14",
    duration: "36 Weeks | 2 Sessions/Week | 55 Min/Session",
    aim: "To understand reinforcement learning, create intelligent agents that learn through interaction, and develop autonomous decision-making systems.",
    units: [
      { no: 1, topic: "Reinforcement Learning Basics", skills: "Agents, environments, rewards, policies" },
      { no: 2, topic: "Q-Learning & DQN", skills: "Value-based learning algorithms" },
      { no: 3, topic: "Policy Gradient Methods", skills: "REINFORCE, Actor-Critic algorithms" },
      { no: 4, topic: "Game Playing AI", skills: "Build agents for games and simulations" },
      { no: 5, topic: "Robotics & Control", skills: "Autonomous robot learning" },
      { no: 6, topic: "Multi-Agent Systems", skills: "Agents that learn and interact together" },
      { no: 7, topic: "Real-World Applications", skills: "Autonomous vehicles, game bots" },
      { no: 8, topic: "RL Capstone Projects", skills: "Build complete autonomous systems" },
    ],
  },
  {
    levelNumber: "7",
    titleKey: "t35",
    subtitle: "Generative AI & LLMs",
    ageGroup: "Ages 14-15",
    duration: "36 Weeks | 2 Sessions/Week | 60 Min/Session",
    aim: "To master generative models including GANs, diffusion models, and large language models, understanding how AI creates text, images, and media.",
    units: [
      { no: 1, topic: "Generative Adversarial Networks", skills: "How GANs generate synthetic data" },
      { no: 2, topic: "Variational Autoencoders", skills: "Learning latent representations" },
      { no: 3, topic: "Diffusion Models", skills: "Image generation and text-to-image" },
      { no: 4, topic: "Large Language Models", skills: "Fine-tuning GPT and BERT models" },
      { no: 5, topic: "Prompt Engineering", skills: "Crafting effective AI prompts" },
      { no: 6, topic: "Text Generation", skills: "Story writing and code generation with AI" },
      { no: 7, topic: "Multimodal AI", skills: "Vision and language combined models" },
      { no: 8, topic: "Generative AI Applications", skills: "Create with AI tools and APIs" },
    ],
  },
  {
    levelNumber: "8",
    titleKey: "t33",
    subtitle: "AI Engineering & Production Systems",
    ageGroup: "Ages 15-16",
    duration: "36 Weeks | 2 Sessions/Week | 60 Min/Session",
    aim: "To develop production-ready AI systems, understand deployment, scaling, monitoring, and ethical considerations for real-world AI applications.",
    units: [
      { no: 1, topic: "Model Deployment", skills: "Deploy models with Docker and cloud platforms" },
      { no: 2, topic: "MLOps Fundamentals", skills: "CI/CD for machine learning" },
      { no: 3, topic: "Model Monitoring & Maintenance", skills: "Track performance and drift in production" },
      { no: 4, topic: "Scalability & Performance", skills: "Optimize models for speed and memory" },
      { no: 5, topic: "AI Security & Privacy", skills: "Adversarial robustness and data privacy" },
      { no: 6, topic: "Ethical AI & Responsible AI", skills: "Fairness, transparency, accountability" },
      { no: 7, topic: "AI Research & Papers", skills: "Read and implement cutting-edge research" },
      { no: 8, topic: "Capstone AI Project", skills: "Build, deploy, and present an AI solution" },
    ],
  },
];
