import type { LevelConfig } from "./types";

export const levelConfigs: LevelConfig[] = [
  {
    type: "single",
    levelNumber: "1",
    titleKey: "t15",
    focus: "Purification (Tahaarah) & Prayer (Salah) - Foundational concepts",
    aim: "To introduce students to the essentials of Islamic worship, beginning with correct purification and the performance of the five daily prayers.",
    topics: [
      "Purification (At-Tahaarah)",
      "Characteristics of ablution (Sifat Al-Wudhooʼ)",
      "The obligatory prayers (As-Salawaat Al-Mafrooda)",
      "Characteristics of the prayer (Sifat As-Salah)",
      "At-Tashahhud",
      "Salutation upon the Prophet (صلى الله عليه وسلم)",
      "Nullifiers of the prayer (Nawaaqiḍ As-Salah)",
    ],
  },
  {
    type: "dual",
    levelNumber: "2",
    titleKey: "t18",
    focus: "Revision & Expansion - Ablution, Supplication & Prayer",
    aim: "To consolidate Level 1 knowledge and introduce students to the opening supplication of prayer, nullifiers of ablution, and deeper aspects of Salah.",
    section1: [
      "Revision of all that has been taught in Level 1",
      "Cleanliness with water and other than it",
      "Characteristics of ablution (Sifat Al-Wudhooʼ)",
      "Nullifiers of ablution (Nawaaqiḍ Al-Wudhooʼ)",
      "The opening supplication for Salah (Duʼāʼ Al-Istiftaah)",
    ],
    section2: [
      "Revision of all that has been taught in Section 1",
      "The obligatory prayers (As-Salawaat Al-Mafrooda)",
      "At-Tashahhud",
      "Salutation upon the Prophet (صلى الله عليه وسلم)",
      "Supplications to seek refuge in after salutation upon the Prophet",
      "Characteristics of the prayer (Sifat As-Salah)",
      "Nullifiers of the prayer (Nawaaqiḍ As-Salah)",
    ],
  },
  {
    type: "dual",
    levelNumber: "3",
    titleKey: "t48",
    focus:
      "Manners of Relieving Oneself, Conditions & Obligations of Ablution, Dry Ablution & Prayer",
    aim: "To teach the correct manners of the lavatory, the conditions and obligations of wudhooʼ, introduction to tayammum, and the conditions and pillars of the prayer.",
    section1: [
      "Revision of all that has been taught in Level 2",
      "Manners of relieving oneself (Aadaab Qadhaʼ Al-Haajah)",
      "Cleanliness with water and stone (Al-Istinjaaʼ wal-Istijmaar)",
      "Removal of impurity (Izaalat An-Najaasah)",
      "Conditions of ablution (Shurooṭ Al-Wudhooʼ)",
      "Obligations of ablution (Waajibaaat Al-Wudhooʼ)",
    ],
    section2: [
      "Revision of all that has been taught in Section 1",
      "Dry ablution (At-Tayammum)",
      "Times of prayer (Awqaat As-Salah)",
      "Conditions of the prayer (Shurooṭ As-Salah)",
      "Pillars of the prayer (Arkaan As-Salah)",
      "Obligatory acts of the prayer (Waajibaat As-Salah)",
    ],
  },
  {
    type: "dual",
    levelNumber: "4",
    titleKey: "t24",
    focus:
      "Comprehensive Wudhooʼ, Adhaan, Prayer Conditions & Detailed Explanations of Prayer Texts",
    aim: "To provide a thorough study of ablution, the call to prayer, times and conditions of Salah, and detailed explanation of key prayer recitations including Surah Al-Faatihah and At-Tashahhud.",
    sectionTitle1: "Lesson 1",
    sectionTitle2: "Lesson 2",
    section1: [
      "Introduction",
      "Revision of all that has been taught in Level 3",
      "Ablution (Al-Wudhooʼ) - comprehensive review",
      "Conditions of ablution (Shurooṭ Al-Wudhooʼ)",
      "Obligations of ablution (Waajibaat Al-Wudhooʼ)",
      "Sunan (Prophetic guidance) of ablution",
      "Nullifiers of ablution (Nawaaqiḍ Al-Wudhooʼ)",
      "The call to prayer and its establishment (Al-Adhaan wal-Iqaamah)",
      "Prophetic guidance on the call to prayer (Sifat Al-Adhaan)",
      "Conditions of the prayer (Shurooṭ As-Salah)",
    ],
    section2: [
      "Revision of all that has been taught in Lesson 1",
      "Times of the obligatory prayers (Awqaat As-Salawaat Al-Mafrooda)",
      "Pillars of the prayer (Arkaan As-Salah)",
      "Obligatory acts of the prayer (Waajibaat As-Salah)",
      "Difference between the pillars and obligations of the prayer",
      "Explanation of Surah Al-Faatihah",
      "Explanation of the meaning of At-Tashahhud",
      "Explanation of the salutation upon the Prophet صلى الله عليه وسلم",
      "Revision Catalogue",
    ],
  },
  {
    type: "dual",
    levelNumber: "5",
    titleKey: "t27",
    focus:
      "Classification of Water, Advanced Wudhooʼ Topics, Full Prayer Description, Congregational Prayer & Voluntary Prayers",
    aim: "To give students a detailed understanding of water classifications, wiping over leather socks, dry ablution, a complete description of prayer including prostration of forgetfulness, and a thorough grounding in congregational prayer and voluntary prayers.",
    sectionTitle1: "Lesson 1",
    sectionTitle2: "Lesson 2",
    section1: [
      "Introduction",
      "Revision of all that has been taught in Level 4",
      "Classification of water (Aqsaam Al-Maaʼ)",
      "Wiping over the shoes/socks (Al-Mash ʼalaa Al-Khuffayn)",
      "Dry ablution (At-Tayammum) - detailed study",
      "The prayer (As-Salah) - comprehensive overview",
      "Manners of walking to prayer and waiting for it",
      "Characteristics of the prayer (Sifat As-Salah) - detailed",
      "Sunan (recommended acts) of the prayer",
      "Detested acts in the prayer (Makroohaat As-Salah)",
      "Prostration of forgetfulness (Sujood As-Sahw)",
    ],
    section2: [
      "Introduction",
      "Revision of all that has been taught in Lesson 1",
      "Congregational prayer (As-Salah Al-Jamaaʼah)",
      "Rulings of leadership (Ahkaam Al-Imaamah)",
      "Position of the Imam and those praying behind him",
      "The maʼmoom following the Imam (Al-Iqtidaaʼ)",
      "Ruling of the masboq (one who misses some of the prayer)",
      "Permissible excuses for leaving off the congregational prayer",
      "Prayer of the people with excuses (Salah Ahl Al-Aʼdhar)",
      "The voluntary prayer (At-Tatawwuʼ)",
      "Prohibited times for praying (Awqaat An-Nahy)",
      "Revision Catalogue",
    ],
  },
];
